### PR TITLE
Add VatNotif

### PR DESCRIPTION
**Pull request by kristiankunc**
Add VatNotif into the _Others_ category (https://vatnotif.kristn.co.uk/)

### CODE REVIEW

**Comment by Epse** [comment]
Hi! Thanks for the PR. This repo collects awesome open source projects in the VATSIM sphere, is there a source link for vatnotif?

**Comment by kristiankunc** [comment]
Yes, forgot to link them initially. The project is fully open source:
https://github.com/kristiankunc/VatNotif-web
https://github.com/kristiankunc/VatNotif-api

**Comment by Epse** [comment]
If you could add the source links in the commit as well then I'll gladly accept this PR

**Comment by kristiankunc** [comment]
I've changed the link to the github rather than the website

**Comment by Epse** [comment]
Hmm when I click that link now, it goes to https://github.com/Epse/awesome-vatsim/github.com/kristiankunc/vatnotif-web which doesn't work...

So sorry for being nitpicky, but could you just add the protocol in there so it isn't interpreted as a relative link?

**Pull request merged**
